language: node_js
node_js:
  - "7"

cache: yarn

services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE dbtest; USE dbtest; CREATE TABLE `test` (`id` int(11) unsigned NOT NULL AUTO_INCREMENT, `rowname` varchar(50) DEFAULT NULL, PRIMARY KEY (`id`)); INSERT INTO `test` (`rowname`) VALUES ("testItem");'

script: npm test

env:
  - DATABASE=dbtest

jobs:
  include:
    - stage: lint
      script: npm run lint
    # - stage: deploy
    #   script: ./deploy