language: node_js
node_js:
  - "7"

cache: yarn

env:
  - DATABASE=dbtest

jobs:
  include:
    - stage: lint
      script: npm run lint
    # - stage: test
    #   script: npm test
    # - stage: deploy
    #   script: ./deploy